export const ADD_PORTRAITS = 'ADD_PORTRAITS';
export const PORTRAITS_LOADING = 'PORTRAITS_LOADING';
export const PORTRAITS_FAILED = 'PORTRAITS_FAILED';

export const ADD_LANDSCAPES = 'ADD_LANDSCAPES';
export const LANDSCAPES_LOADING = 'LANDSCAPES_LOADING';
export const LANDSCAPES_FAILED = 'LANDSCAPES_FAILED';

export const ADD_WILDLIFE = 'ADD_WILDLIFE';
export const WILDLIFE_LOADING = 'WILDLIFE_LOADING';
export const WILDLIFE_FAILED = 'WILDLIFE_FAILED';

export const ADD_ITEMS = 'ADD_ITEMS';
export const ITEMS_LOADING = 'ITEMS_LOADING';
export const ITEMS_FAILED = 'ITEMS_FAILED';

export const ADD_MESSAGE = 'ADD_MESSAGE';
